server:
    port: 8090

spring:
  application:
    name: mcsv-student
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentsDB
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka