server:
  port: 9090

spring:
  application:
    name: mcsv-course
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursesDB
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
